name: adaptive_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Plugins de video
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^5.1.2

  # UI y utilidades
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  split_view: ^3.2.1

  # HTTP, Google y autenticación
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  http: ^1.2.1

  # Estado, rutas y enlaces
  provider: ^6.1.2
  go_router: ^14.1.1
  url_launcher: ^6.3.0

  # Paquetes para el servidor proxy y variables de entorno
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Registra el archivo .env para que la app pueda usarlo
  assets:
    - .env